### ISSUE TITLE
Catching exceptions with sentry

### ISSUE THREAD

**Issue by pjotterplotter** [ciscorn/starlette-graphene3#13]
Currently all exceptions are catched and returned in a formatted form. This is fine for invalid formatted queries, but for programming errors in my code i'd like these to be reraised, so i can catch them with Sentry for example. I could not find a way to achieve this currently, any ideas?

**Comment by ciscorn** [comment]
Hi @pjotterplotter 
I just added exception reporting with the `logging` module.

Your Sentry setup will automatically captures logging outputs by default.
https://docs.sentry.io/platforms/python/guides/logging/
