### ISSUE TITLE
logger can't be disable 

### ISSUE THREAD

**Issue by ivancallekira** [ciscorn/starlette-graphene3#19]
Hey, I've been using `starlette-graphene3` and I've got into a small issue.

When I want to signal an error (i.e. an entity not found) I raise a Python exception. The exact exception type depends on the type of error. I then catch all these errors in a middleware to log them, and re-raise them as GraphQLError's to send an appropriate error response to the client. This package then logs the error too, so it's logged twice. I would like these errors not to be logged again by the package.

I think that a possible solution is for you to implement an optional error handler, such that only the errors that I don't catch are logged. That could be in the form of a callback, passed to the app's constructor.

**Comment by ciscorn** [comment]
Hi @ivancallekira 

You can disable the Python's logger by doing the following:

```python
import logging
logger = logging.getLogger("starlette_graphene3")
logger.disabled = True
```

Does this solve your problem? (If it solves, I'll document it in README.md.)

**Comment by ivancallekira** [comment]
Hi @ciscorn,

This solution solves the problem of errors being logged twice. However, I like the idea of `starlette_graphene3` logging errors, as I can get exceptions not caught by graphene's middlewares. For example, an error in schema validation (e.g. a client requesting a field that doesn't exit) is not caught by any middleware, but is currently being logged by starlette_graphene3's logger. Ideally, I would like to catch errors like this to log them myself. I think an optional error handler feature in starlette_graphene3's app would solve that problem.

Many thanks

**Comment by ciscorn** [comment]
@ivancallekira Thanks for the explanation.

Can the `error_formatter` callback play that role?

```python
from graphql import format_error
import logging

def my_format_error(error):
    if error.original_error:
        # your logging code here
        return {"message": "server error"}
    else:
        # your logging code here
        return format_error(error)

logger = logging.getLogger("starlette_graphene3")
logger.disabled = True

app.mount("/", GraphQLApp(schema, error_formatter=my_format_error))
```

**Comment by ivancallekira** [comment]
Hi @ciscorn,

Yes, I was thinking about a specific function to handle the error, but your solution does solve my problem.

Cheers,
