### ISSUE TITLE
Version 0.2.1 on PyPI does not contain the latest commit

### ISSUE THREAD

**Issue by abompard** [ciscorn/starlette-graphene3#3]
It's a bit weird but it looks like the tarball of 0.2.1 that can be found on PyPI does not contain commit ae328c, even though it should be according to the commit history. Not sure how that could happen, maybe I'm missing something too obvious.

**Comment by ciscorn** [comment]
Thanks for letting me know. I don't know what made it happen either.

Anyway, I'll try to update the PyPI package to fix this issue.
