### ISSUE TITLE
Is there a playground for websocket routes?

### ISSUE THREAD

**Issue by Pet3ris** [ciscorn/starlette-graphene3#8]
Hi There,

I'm using the following code to run a websocket GraphQL endpoint:

```python
"""Main server application."""

import asyncio

import graphene

from starlette.applications import Starlette
from starlette_graphene3 import GraphQLApp
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware

from .schema import schema_basic

middleware = [
    Middleware(
        CORSMiddleware,
        allow_origins=['*'],
        allow_methods=['POST', 'GET'],
        allow_headers=['access-control-allow-origin', 'authorization', 'content-type']
    )
]

app = Starlette(debug=True, middleware=middleware)
gapp = GraphQLApp(schema_basic(), playground=True)
app.add_route("/graphql", gapp)
app.add_websocket_route("/graphql-ws", gapp)
```

How do I now debug the new websocket route in the playground?

1.

Opening up playground with `localhost:5000/graphql-ws` doesn't work

2.

Opening up playground with `localhost:5000/graphql` works but then when running the subcription, it's attempting to connect to the server on the incorrect route (`/graphql`).

![image](https://user-images.githubusercontent.com/224585/116276590-91de9980-a77c-11eb-9ff8-a6a795f94dfb.png)

Any thoughts on how to figure out if the websocket endpoint is working?

**Comment by ciscorn** [comment]
Hi @Pet3ris,

Which ASGI server are you using?

If you are using Uvicorn, you need to install the `websockets` or `uvicorn[standard]` package.

```
pip3 install websockets
```

<img width="758" alt="Screen Shot 2021-04-29 at 2 17 51" src="https://user-images.githubusercontent.com/5351911/116445729-276b4d80-a891-11eb-8df0-f0d59cb3d875.png">

**Comment by Pet3ris** [comment]
@ciscorn yeah I'm using `uvicorn[standard]`:

```
uvicorn = {extras = ["standard"], version = "^0.13.4"}
starlette = "^0.14.2"
starlette-graphene3 = "^0.3.0"
```

**Comment by ciscorn** [comment]
@Pet3ris 

I've added `playground_options` parameter to `starlette-graphene3==0.3.2`, which allows you to do something like this:

```
GraphQLApp(schema, playground=True, playground_options={"subscriptionEndpoint": "/graphql-ws"})
```

**Comment by Pet3ris** [comment]
Wow that immediately works:

![image](https://user-images.githubusercontent.com/224585/116528535-da5c9b00-a8d3-11eb-987b-d93c17f83250.png)

Appreciate the blitz release!
